lib/next_ls.ex
lib/next_ls/diagnostic_cache.ex
lib/next_ls/extensions/elixir_extension.ex
lib/next_ls/lsp_supervisor.ex
lib/next_ls/runtime.ex
priv/monkey/_next_ls_private_compiler.ex
test/next_ls/extensions/elixir_extension_test.exs
test/next_ls/runtime_test.exs
test/next_ls_test.exs
test/support/project/lib/bar.ex

Introduce the "extension" concept and creates the ElixirExtension, which
provides Elixir compiler diagnostics.
TODO: Correct the column information on the diagnostics. I think there
are some commits on main that fix some of this. But there are Tokenizer
diagnostics that need some massaging as well.
The interface for extensions also needs to to be finalized.
Extension diagram
```mermaid
sequenceDiagram
NextLS->>ExtensionFoo: start_child
NextLS->>ExtensionBar: start_child
NextLS->>NextLS.Runtime: start_child
NextLS-->>Task.Supervisor: wait for runtime
loop Until Runtime Ready
Task.Supervisor->>NextLS.Runtime: ready?
NextLS.Runtime->>Task.Supervisor: no
end
NextLS.Runtime->>Task.Supervisor: yes
Task.Supervisor-->>NextLS: ready!
NextLS-->>Task.Supervisor: ask to compile …
```

feat(elixir): compiler diagnostics

---

lib/next_ls.ex
lib/next_ls/lsp_supervisor.ex
lib/next_ls/runtime.ex
test/next_ls/runtime_test.exs
test/next_ls_test.exs

This lets the compiler stdout messgaes to be logged to the client while
the RPC is still happening.
Previously, the port would message back to the process that was
synchronously waiting on the RPC to finish, so it didn't send any log
messages to the LSP process until the compiler was done.
This made it look like the initial compiler was hanging.
Fixes #60

fix: run compiler in task

---

README.md
lib/next_ls/lsp_supervisor.ex
lib/next_ls/symbol_table.ex

fix: add .gitignore file to .elixir-tools directory

---

lib/next_ls.ex
test/next_ls_test.exs

feat: workspace folders on startup

---

lib/next_ls.ex

- fix: reap symbols when file is deleted
- fix: correctly format files

2023 07 27 format correctly

---

lib/next_ls.ex
test/next_ls_test.exs

This PR is meant to implement the [Find References Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_references).
The strategy is as follows:
1. Identify what kind of symbol we looking for
1. Check the `symbols` table to see if we are in a definition: `defmodule`, `def`, `defp`, `defmacro` or `defstruct`
2. If we are not in a definition, check the `references` table to see if we are in a function call or in a module alias.
2. Once we know what kind of symbol we are looking for (either a module or a function), check the `references` table to list all known references.
I've been using this today at $DAYJOB, which is a pretty big codebase, and everything seems to work just fine. I've also added two automated tests to confirm …

feat: find references

---

README.md

This pull request adds a brief explanation to the README about how to start the NextLS server locally and connect your editor to it.
I added the VSCode configuration since that's what I use and the NeoVim configuration since @mhanberg posted it on Discord 😅

Add dev instructions to README

---

lib/next_ls/extensions/elixir_extension.ex
lib/next_ls/runtime.ex
test/next_ls/runtime_test.exs
test/next_ls/workspaces_test.exs
test/support/utils.ex

Playing around with Next LS this morning and was running up against some issues compiling a project of mine. I think the previous handling of `:badrpc` errors was incorrect, which was hiding certain errors of causing them to bubble up in weird ways (like trying iterate over an atom).

fix: improve error handling for compiler diagnostics

---

lib/next_ls.ex
lib/next_ls/db.ex
lib/next_ls/db/schema.ex
lib/next_ls/definition.ex
lib/next_ls/runtime.ex
lib/next_ls/runtime/supervisor.ex
test/next_ls_test.exs

1. Create the `schema` table if needed. This includes a version column.
2. If the max version selected from the `schema` table is equal to the current version, we noop and halt.
Else, if the max version is less than the current one (compiled into this module) or nil
we "upgrade" the database.
3. Unless halting, we drop the non-meta tables, and then create them from scratch
4. Return a value to signal to the caller that re-indexing is necessary.

refactor: migration system

---

.github/workflows/ci.yaml

I noticed `mix dialyzer` takes >= 1 minute, of which only 4 seconds is dialyzer. This PR should ensure that the built dependencies are also cached.

ci: add build cache to dialyzer

---

lib/next_ls.ex
lib/next_ls/db.ex
lib/next_ls/runtime/sidecar.ex
priv/monkey/_next_ls_private_compiler.ex

This pull request stops cleaning file references on every file save and, instead, cleans them only when we compile the file.
On the one hand we stop cleaning the file references on the `TextDocumentDidSave` notification. On the other hand we now clean the references on the `:start` event of the compiler tracer.
As per [the Elixir docs](https://hexdocs.pm/elixir/Code.html#module-compilation-tracers):
> `:start` - (since v1.11.0) invoked whenever the compiler starts to trace a new lexical context. A lexical context is started when compiling a new file or when defining a module within a function
Since this is only executed when compiling a file or defining a module we know that it is safe to to clean references at this point, since new ones will be populated during the compilation that just …

Don't clean references on every file save

---

.github/workflows/ci.yaml

ci: don't cache _build and deps for dialyzer
this is causing some weird problem where it can't find dialyzer, the
added CI time is worth passing builds for now

ci: don't cache _build and deps for dialyzer

---

mix.lock

fix: update burrito
This update will print the burrito log message to stderr instead of
stdout, which should stop it from crashing in Visual Studio Code when it
updates itself.

fix: update burrito

---

README.md

Once helix releases the next version, I'll revert this and update the docs.

docs: update helix instructions for nightly version

---

.rtx.toml

This also reorders Erlang and Elixir so that rtx installs Erlang first.
This is helpful for anyone using a .default-mix-commands to
automatically install archives when rtx installs Elixir.

fix: use otp26-compiled version of Elixir

---

config/config.exs

This makes error logs show up in VSCode's error window without
interfering with communication over stdout.

fix: redirect logger to stderr

---

lib/next_ls.ex
test/next_ls_test.exs

This is an implementation of a sequential fuzzy string matching algorithm, similar to those used in code editors like Sublime Text. It is based on Forrest Smith's work on https://github.com/forrestthewoods/lib_fts/ and his blog post https://www.forrestthewoods.com/blog/reverse_engineering_sublime_texts_fuzzy_match/

ranked fuzzy match search of workspace symbols

---

lib/next_ls.ex
lib/next_ls/ast_helpers.ex
lib/next_ls/db.ex
lib/next_ls/definition.ex
lib/next_ls/runtime/sidecar.ex
priv/monkey/_next_ls_private_compiler.ex
test/next_ls/definition_test.exs
test/next_ls/references_test.exs

resolves #86 
Parses AST to collect module attribute definitions. Also parses AST to get attribute reference name.

feat: module attributes

---

lib/next_ls/ast_helpers.ex
lib/next_ls/db.ex
lib/next_ls/definition.ex
lib/next_ls/runtime/sidecar.ex
priv/monkey/_next_ls_private_compiler.ex
test/next_ls/ast_helpers_test.exs
test/next_ls/definition_test.exs
test/next_ls/references_test.exs

Collects references to modules in alias calls, which allows you do use go to definition and find references on them
```elixir
alias Foo.Bar.Baz
alias Foo.Bar.{Baz, Bing}
alias Foo.Bar.{
Baz,
Bing
}
```

feat: go to definition when aliases modules

---

lib/next_ls.ex
lib/next_ls/runtime.ex
mix.exs
test/next_ls/runtime_test.exs

Support passing `target` and `env` options from LSP

---

lib/next_ls.ex

fix: don't fail when document is missing
There is a report of the document being nil, which is causing the server
to crash. The document should never be nil, but we can figure that out
later. The server not crashing should make that easier.

fix: don't fail when document is missing

---

README.md

The `$` in front of the command was causing `command not found: $` error when using the copy button next to the snippet in the README.md file.

Fix installation commands copying in the README.md

---

lib/next_ls.ex

This fixes the following exception that I started getting with VSCode
1.82.3:
```
** (CaseClauseError) no case clause matching: "attribute"
(next_ls 0.13.4) lib/next_ls.ex:337: NextLS.handle_request/2
(gen_lsp 0.6.0) lib/gen_lsp.ex:248: anonymous fn/5 in GenLSP.loop/3
(gen_lsp 0.6.0) lib/gen_lsp.ex:308: GenLSP.attempt/3
(stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```
Fixes #280.

Ignore unknown reference types

---

lib/next_ls/helpers/ast_helpers/variables.ex
test/next_ls/helpers/ast_helpers/variables_test.exs

Until search for local variables done on a fly it should ignore broken source code.

fix: correctly process broken code when searching local variables

---

flake.nix

Solve #278.
- Rename `burrito_out/next_ls_<system>_<arch>` to `burrito_out/nextls`, which is the command to install.
- Remove the original `bin` directory containing the `next_ls` app that isn't expected to be installed, then rename `burrito_out` directory to `bin`.
```shell
gh repo clone elixir-tools/next-ls
gh co 283
nix profile install .
nextls --version
```
<details>
<summary>It works in Doom Emacs to format a buffer after saving it.</summary>
- config.el
```emacs-lisp
(use-package! elixir-mode
:hook (before-save . elixir-format-before-save)
:config
(defun elixir-format-before-save ()
(when (derived-mode-p 'elixir-mode)
(eglot-format-buffer))))
```
- Eglot events log
```
[client-request] (id:9) Wed Oct 11 00:02:12 2023:
(:jsonrpc "2.0" :id 9 :method "textDocument/formatting" :params …
```

Fix nextls command not found when installing with Nix

---

README.md
lib/next_ls.ex
lib/next_ls/autocomplete.ex
lib/next_ls/db.ex
lib/next_ls/helpers/ast_helpers/variables.ex
lib/next_ls/runtime.ex
lib/next_ls/snippet.ex
test/next_ls/autocomplete_test.exs
test/next_ls/completions_test.exs
test/next_ls/helpers/ast_helpers/variables_test.exs

Implements basic autocompletion.
Current completion candidates supported
- Global modules
- Global Structs
- Struct fields
- Remote functions (w/ documentation)
- Special Forms
- Bitstring modifiers
- filesystem paths in strings
More features, particularly features that rely on contextual information about the code itself (meaning, which identifiers, aliases, imports are available) will come in subsequent patches.
Partially addresses #45 
This patch also introduces a new initialization option, `experimental`.
This feature will be gated as an experimental feature as it's built out. The purpose of this is so that early-early adopters can try it out and report bugs, but folks who would rather wait for something more stable won't have it affect their workflows.
To enable this feature, toggle …

feat: completions

---

flake.nix

Regarding `HOME` specifically, I would've liked to eliminate that too as it's nearly always a pungent smell in Nix builds, but [Burrito.Steps.Build.PackAndBuild](https://github.com/burrito-elixir/burrito/blob/a60c6ab21156fc4c788907d33bfd0c546a022272/lib/steps/build/pack_and_build.ex#L26-L38) seems to
want a writable path to work in. AFAICT it's purely for scratch space, so we can just directly reuse the Nix build's temporary directory.

refactor: reduce imperative shell logic in flake.nix

---

.github/workflows/ci.yaml
flake.nix

This PR is a follow up to #312 and is intended to:
- Save time on CI
- Make the binaries immediately available to Nix users
by pushing newly built Nix assets to your cachix account.
As extra steps, you will have to:

ci: add cachix-action

---

lib/next_ls.ex

This fixes a no case clause matching "attribute" exception seen in VSCode.

fix: vscode sends an another "attribute"

---

lib/next_ls/updater.ex

This is a minimal fix to the crash reported in #350 - e.g. Github API returns a 403 or other non-200 error. (Github's API docs do not make it easy to find the response schema for errors, only successes, unfortunately.)
Fixes #350

fix: handle when auto updater receives a non-200 from GitHub API

---

flake.nix

By default, the BEAM package set on Nix depends on xwidgets, but this would be unnecessary for this language server. Nixpkgs provides [multiple variants of BEAM](https://github.com/NixOS/nixpkgs/blob/110f464d081a7f3cda85c5068f959814dd358958/pkgs/top-level/all-packages.nix#L17577-L17583):
```nix
beam = callPackage ./beam-packages.nix { };
beam_nox = callPackage ./beam-packages.nix { beam = beam_nox; wxSupport = false; };
beam_minimal = callPackage ./beam-packages.nix {
beam = beam_minimal;
wxSupport = false;
systemdSupport = false;
};
```
The minimal version would be sufficient for this project. With this change, downloading time of the Nix package will be reduced.

chore(nix): use beam_minimal to remove xwidgets dependency

---

lib/next_ls/helpers/hover_helpers.ex
test/next_ls/helpers/hover_helpers_test.exs

This handles the conversion of the description list tag to Markdown.
Markdown doesn't support what can be done with the dl tag, but this
renders something legible for the few cases it's used.
Here's how it looks for `:init.get_argument/1`:
Fixes #361

Minimally support dl tag for Erlang hover docs

---

lib/next_ls/autocomplete.ex
test/next_ls/autocomplete_test.exs

Add autocomplete for Kernel functions like `put_in/2`, `++/2`, `defstruct/1`

feat: autocomplete for kernel functions

---

lib/next_ls/extensions/elixir_extension.ex
lib/next_ls/extensions/elixir_extension/code_action.ex
lib/next_ls/extensions/elixir_extension/code_action/require.ex
test/next_ls/extensions/elixir_extension/code_action/require_test.exs
test/next_ls/extensions/elixir_extension/code_action/unused_variable_test.exs
test/next_ls/extensions/elixir_extension/code_action_test.exs

This adds a require code action that adds `require Module` to your module whenever a macro is used without requiring it beforehand.
It tries to insert the require after all the top level Elixir macros(moduledoc, alias, require, import).

feat: add require code action

---

.github/workflows/release.yaml

The new github ci job to publish next-ls to homebrew seems to be broken https://github.com/elixir-tools/next-ls/actions/runs/7997177802/job/21841392167
This should fix it.

fix: homebrew release

---

lib/next_ls.ex
lib/next_ls/runtime.ex
test/next_ls/dependency_test.exs

fix: prompt the user to run mix deps.get when dependency problems happen at runtime

---

lib/next_ls.ex
lib/next_ls/snippet.ex

feat: add snippets

---

lib/next_ls.ex
lib/next_ls/autocomplete.ex
lib/next_ls/helpers/ast_helpers/env.ex
test/next_ls/autocomplete_test.exs
test/next_ls/helpers/ast_helpers/env_test.exs

feat(completions): local variables

---

lib/next_ls.ex
lib/next_ls/helpers/ast_helpers/env.ex
lib/next_ls/snippet.ex
test/next_ls/completions_test.exs
test/next_ls/snippet_test.exs

defmodule snippet infer module name
recording 🎥 
https://github.com/elixir-tools/next-ls/assets/5053083/e5e6aaa4-5a63-467b-b41f-49f6fd35a47a

feat: defmodule snippet infer module name

---

lib/next_ls.ex
lib/next_ls/progress.ex
lib/next_ls/runtime.ex
lib/next_ls/runtime/supervisor.ex
priv/monkey/_next_ls_private_compiler.ex
test/next_ls/autocomplete_test.exs
test/next_ls/dependency_test.exs
test/next_ls/extensions/credo_extension_test.exs
test/next_ls/runtime_test.exs

Hopefully solves the following issues
#285 
#392
#389
#284
#274
#211
#115

fix: single thread compiler requests

---

lib/next_ls.ex
lib/next_ls/helpers/ast_helpers.ex
lib/next_ls/helpers/ast_helpers/env.ex
test/next_ls/helpers/ast_helpers/env_test.exs

fix(completions): log source code when env fails to build

---

priv/monkey/_next_ls_private_compiler.ex
test/next_ls/completions_test.exs

fix(completions): completions inside alias/import/require special forms

---

lib/next_ls.ex
priv/monkey/_next_ls_private_compiler.ex
test/next_ls/completions_test.exs

The `test/2` macro is an example of this
Closes #420

fix(completions): imports inside blocks that generate functions

---

lib/next_ls.ex
lib/next_ls/db.ex
lib/next_ls/db/schema.ex
lib/next_ls/definition.ex

Closes #342
Closes #184
Closes #304

fix(references,definition): better references of symbols

---

lib/next_ls/helpers/ast_helpers.ex
test/next_ls/helpers/ast_helpers_test.exs

Previously this function did not account for columns, which produced
inaccurate results for some edge cases

fix: accuracy of get_surrounding_module

---

lib/next_ls/runtime.ex
priv/monkey/_next_ls_private_compiler.ex

fix(runtime): remove unused variable warnings

fix(runtime): use correct path for bundled elixir

---

lib/next_ls.ex
lib/next_ls/runtime.ex
lib/next_ls/runtime/bundled_elixir.ex

fix: correctly set MIX_HOME when using bundled Elixir

---

flake.nix

Work in progress trying to fix `next-ls` for NixOS.

Copy files over first, then apply patchelf

---

lib/next_ls.ex
lib/next_ls/progress.ex
lib/next_ls/runtime.ex
test/support/utils.ex

fix: use unified logger in more places

fix: respect client capabilities

---

lib/next_ls.ex
lib/next_ls/autocomplete.ex
lib/next_ls/snippet.ex

feat: include `do` as a completions item/snippet

---

lib/next_ls/runtime.ex
priv/monkey/_next_ls_private_compiler.ex

Frequently we'd see the following error in tests, and some users were
seeing in production:
```
[error] Bad RPC call to node nextls-runtime-1715431446385794000@MacBook-XXX: {:EXIT, {:badarg, [{:ets, :lookup, [:elixir_config, :parser_options], [error_info: %{cause: :id, module: :erl_stdlib_errors}]}, {:elixir_config, :get, 1, [file: ~c"src/elixir_config.erl", line: 21]}, {:elixir_compiler, :string, 3, [file: ~c"src/elixir_compiler.erl", line: 7]}, {Module.ParallelChecker, :verify, 1, [file: ~c"lib/module/parallel_checker.ex", line: 112]}, {Code, :compile_file, 1, []}]}}
```
I believe that this is caused by an internal ETS table not being booted
yet, so we not await on it being present on the project node.
Closes #467

fix: ensure some elixir internals are ready

---

config/dev.exs
config/prod.exs
config/test.exs
lib/next_ls.ex
lib/next_ls/autocomplete.ex
lib/next_ls/db.ex
lib/next_ls/db/activity.ex
lib/next_ls/definition.ex
lib/next_ls/document_symbol.ex
lib/next_ls/extensions/credo_extension.ex
lib/next_ls/extensions/elixir_extension.ex
lib/next_ls/extensions/elixir_extension/code_action/require.ex
lib/next_ls/helpers/ast_helpers.ex
lib/next_ls/helpers/ast_helpers/variables.ex
lib/next_ls/helpers/edit_helpers.ex
lib/next_ls/progress.ex
lib/next_ls/runtime.ex
lib/next_ls/runtime/sidecar.ex
lib/next_ls/snippet.ex
mix.exs
mix.lock
priv/monkey/_next_ls_private_compiler.ex
test/next_ls/autocomplete_test.exs
test/next_ls/commands/pipe_test.exs
test/next_ls/extensions/elixir_extension/code_action/require_test.exs
test/next_ls/extensions/elixir_extension/code_action/undefined_function_test.exs
test/next_ls/extensions/elixir_extension_test.exs
test/next_ls_test.exs

Shows error messages for well defined errors, but we don't receive
any signal that it failed for a plugin being missing, unfortunately.
Closes #463

fix(formatting): show message when it fails

---

lib/next_ls.ex
lib/next_ls/autocomplete.ex

Removes `&` as a trigger character, which will allow completions to
trigger as normal once you start typing after.
This shouldn't be a problem as the only two completions offered by that
are `&` and `&&`, and operators like `||` don't complete anyway.

fix: better completions for function references

---

priv/monkey/_next_ls_private_compiler.ex

In Elixir >= 1.17, the meta will _not_ have a `:column` key if it is
generated by a macro.

fix(index): better heuristic if a reference is from a macro

---

lib/next_ls/docs.ex

This was triggered by hovering over `:gen_tcp.shutdown/2`.

fix: support numbered lists in docs to prevent crash

---

lib/next_ls.ex
lib/next_ls/runtime.ex
lib/next_ls/runtime/bundled_elixir.ex
test/next_ls/autocomplete_test.exs
test/next_ls/runtime_test.exs
test/support/utils.ex

Set `MIX_ARCHIVES` explicitly to make sure to override any existing setting, e.g. from `asdf` or `mise`.
What happens on `main` currently is that `hex` is installed into whatever the environment variable `MIX_ARCHIVES` points at. The var is set by e.g. `mise`. So if the "regular" project setup is running on Elixir < 1.17, its installation of Hex will be overridden by NextLS and it stops working after that.
This patch makes sure to set `MIX_ARCHIVES` explicitly so the `hex` archive ends up in the right place.

fix(runtime): use correct archive locations (e.g. Hex) for bundled Elixir

---

flake.lock
flake.nix
package.nix
release-please-config.json

I split the package out here, and dropped the makeOverridable. I can put this back if needed, but I think separating the package makes it clearer to reason about. It's also more similar to a nixpkgs package this way. :)
I discovered that erlang_27 actually depends on erlang_26 currently for ex_doc, so you have to compile both with beam_minimal. Anybody using your cache won't notice though.
I also wondered if the zig pinned release could be removed in favor of current unstable.

chore(nix): updates to use nixpkgs elixir 1.17

---

flake.lock
flake.nix

Updates the rev of nixpkgs and removes the overrides we discussed before. I submitted next-ls to nixpkgs, so users can install it directly from there now. As a side effect though, beam_minimal erlang_27+elixir_1_17 is now built by hydra and is thus cached. As long as the nixpkgs versions continue to match what is expected here, we shouldn't need to build the dependencies.
https://github.com/NixOS/nixpkgs/pull/324678

chore(nix): update nixpkgs

---

flake.lock
flake.nix
priv/monkey/_next_ls_private_compiler.ex

fix: correctly index imported functions on 1.18
chore: change 1.17.0-dev to 1.17.0
chore(nix): update flake

fix: extract module line from debug info on 1.18
